disabled_rules:
  - file_length
  - function_body_length
  - function_parameter_count
  - identifier_name
  - switch_case_alignment
  - todo
  - type_body_length
  - type_name
  - force_cast
  - trailing_whitespace

opt_in_rules:
  - closing_brace
  - opening_brace
  - return_arrow_whitespace
  - trailing_semicolon
  - statement_position
  - explicit_init
  - shorthand_operator

excluded:
  - Pods

trailing_semicolon: error
empty_count: error
closing_brace: error
opening_brace: error
return_arrow_whitespace: error
statement_position: error
colon: error
comma: error
force_try: warning
force_cast: warning

line_length: 1000